export const SEARCH_FORM_VALUE_CHANGE  = 'search/UPDATE_SEARCH_FORM_VALUE'
export const UPDATE_SEARCH_RESULTS = 'search/UPDATE_SEARCH_RESULTS'

export const EDIT_SIGHTINGS_COUNT = 'species/EDIT_SIGHTINGS_COUNT'
export const INITIAL_SPECIES_LOAD = 'species/INITIAL_SPECIES_LOAD'
